# Saswata Sarkar 19279 
# Department of Data Science Engineering

## Assignment 2 
### Due Date: 26 September 2021, Sunday, 11.00 am

### Example: Basic Numpy

(1) Create a NumPy array with the integers from your birthdate (year,
    month, and day)

(2) Retrieve the year.

(3) Replace the year with the current year.

(4) Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?

In [1]:
import numpy as np

In [2]:
# 1
a = np.array([1986, 12, 24])

In [3]:
# 2
a[0]

1986

In [4]:
# 3
a[0] = 2021

In [5]:
# 4
a = np.arange(567, 890, 3)
a

array([567, 570, 573, 576, 579, 582, 585, 588, 591, 594, 597, 600, 603,
       606, 609, 612, 615, 618, 621, 624, 627, 630, 633, 636, 639, 642,
       645, 648, 651, 654, 657, 660, 663, 666, 669, 672, 675, 678, 681,
       684, 687, 690, 693, 696, 699, 702, 705, 708, 711, 714, 717, 720,
       723, 726, 729, 732, 735, 738, 741, 744, 747, 750, 753, 756, 759,
       762, 765, 768, 771, 774, 777, 780, 783, 786, 789, 792, 795, 798,
       801, 804, 807, 810, 813, 816, 819, 822, 825, 828, 831, 834, 837,
       840, 843, 846, 849, 852, 855, 858, 861, 864, 867, 870, 873, 876,
       879, 882, 885, 888])

In [6]:
a[8]

591

In [7]:
a[15]

612

### Exercise 1 Basic Numpy

(1) Create an array of 10 random integers, from 0-100.

(2) Find the mean and standard deviation of these numbers.  

(3) Create another array of 10 random integers, from 0-100.

(4) Create a new array whose elements are the average of those from
    each of the previous ones.  

(5) Create an array of 10 random floats, from 0-100.

(6) We would expect the mean to be approaximately 50.  Is it?  What's
    the standard deviation?

(7) What are the min and max values?

In [8]:
#1
a = np.random.randint(0,101,10)
print("The randomly generated array is with 10 integers is: ", a)

The randomly generated array is with 10 integers is:  [86  3 57  3 34 26  3 24 39 64]


In [9]:
#2
print(f"The mean and the standard deviation of the array are {a.mean()} and {a.std()} respectively.")

The mean and the standard deviation of the array are 33.9 and 26.841944787961992 respectively.


In [10]:
#3
b = np.random.randint(0,101,10)
print("The other randomly generated array with 10 integers is: ", b)

The other randomly generated array with 10 integers is:  [18 11 99 93 60 85 62 97 41 57]


In [11]:
#4
c = (a+b)/2
print(f"The new array is {c} whose elements are the average of those from each of the previous ones.")

The new array is [52.   7.  78.  48.  47.  55.5 32.5 60.5 40.  60.5] whose elements are the average of those from each of the previous ones.


In [12]:
#5
f = np.random.uniform(0.0, 100.00000001,10)
print("The randomly generated array with 10 float numbers is:\n", f)

The randomly generated array with 10 float numbers is:
 [17.09043106 40.72745841  4.48343054 51.92972226 67.58891032 50.68575057
  3.8072286   0.83421379 13.12742616 13.3079046 ]


In [13]:
#6
if f.mean() == 50: #check if the mean of array 'f' is 50 or not.
    print("The mean of 'f' is 50.")
else:
    print(f"The mean of 'f' is not 50, but it is {f.mean()}.")
print(f"The standard deviation of 'f' is {f.std()}.")

The mean of 'f' is not 50, but it is 26.358247630330887.
The standard deviation of 'f' is 22.851609083823266.


In [14]:
#7
print(f"The maximum and minimum values of the array \n {f} \n is {f.max()} and {f.min()} respectively.")

The maximum and minimum values of the array 
 [17.09043106 40.72745841  4.48343054 51.92972226 67.58891032 50.68575057
  3.8072286   0.83421379 13.12742616 13.3079046 ] 
 is 67.5889103158021 and 0.8342137855891877 respectively.


### Exercise 2 Indexing

(1) Create an array of 20 random integers from 0 to 100.

(2) Find the largest even number.

(3) Find the mean of the odd numbers.

(4) Create a NumPy array from the first and last odd numbers.

(5) Create an array of 20 floats from 0-1,000.

(6) Find the items that are less than the mean.

(7) Find the items less than mean-std.

In [15]:
#1
a = np.random.randint(0,101,20)
print("The randomly generated array is ", a)

The randomly generated array is  [38 33 45 53 10 59 35 37 62 97 99 98 28 84 54  5 32 48 49 70]


In [16]:
#2
even = np.array([x for x in a if x%2==0])
print(f"The largest even number in the array {a} is {even.max()}.")

The largest even number in the array [38 33 45 53 10 59 35 37 62 97 99 98 28 84 54  5 32 48 49 70] is 98.


In [17]:
#3
odd = np.array([x for x in a if x%2 != 0])
print(f"The mean of the odd numbers in {a} is {odd.mean()}")

The mean of the odd numbers in [38 33 45 53 10 59 35 37 62 97 99 98 28 84 54  5 32 48 49 70] is 51.2


In [18]:
#4
odd.sort()
odds = np.arange(odd[0], odd[-1])
print(f"The array generated with the elemnts between the first and last odd number of\n{a} is \n {odds}.")

The array generated with the elemnts between the first and last odd number of
[38 33 45 53 10 59 35 37 62 97 99 98 28 84 54  5 32 48 49 70] is 
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98].


In [19]:
#5
f = np.random.uniform(0.0, 1000.00000001, 20)
print("The randomly generated array with 10 float numbers is:\n", f)

The randomly generated array with 10 float numbers is:
 [441.02392172 120.0861329  798.13388435 882.66880664 923.61198308
 803.55850479 265.20837639 595.90404217 188.69680406 447.43735064
  52.91970644 382.30352332 138.23337035 393.57339058 794.42257223
 619.44078216 840.66122349 343.88952502 578.92759037 113.5826894 ]


In [20]:
#6
less = np.array([x for x in f if x < f.mean()])
print(f"The items that are less than the mean {f.mean()} is {less}.")

The items that are less than the mean 486.2142090044505 is [441.02392172 120.0861329  265.20837639 188.69680406 447.43735064
  52.91970644 382.30352332 138.23337035 393.57339058 343.88952502
 113.5826894 ].


In [21]:
#7
mean_std = np.array([x for x in f if x < (f.mean() - f.std())])
print(f"The items that are less than the difference between the mean and standard deviation of the array \n {f} is {mean_std}")

The items that are less than the difference between the mean and standard deviation of the array 
 [441.02392172 120.0861329  798.13388435 882.66880664 923.61198308
 803.55850479 265.20837639 595.90404217 188.69680406 447.43735064
  52.91970644 382.30352332 138.23337035 393.57339058 794.42257223
 619.44078216 840.66122349 343.88952502 578.92759037 113.5826894 ] is [120.0861329  188.69680406  52.91970644 138.23337035 113.5826894 ]


### Exercise 3 More indexing

(1) Create a NumPy array of 20 random integers from 0-100.

(2) What's the smallest even number greater than the mean?

(3) Show all numbers either < mean-std OR > mean+std.

(4) Show odd numbers < mean and even numbers > mean.

In [22]:
#1
a = np.random.randint(0,101,20)
print("The randomly generated array is ", a)

The randomly generated array is  [73 83 94 69 76 21 31 48 67 77 78  7 55 14 61 57  3 49 66 16]


In [23]:
#2
even = np.array([x for x in a if x%2 == 0 and  x > a.mean()])
print(f"The smallest even number that is greater than the menan is {even.min()}.")

The smallest even number that is greater than the menan is 66.


In [24]:
#3
m, s = a.mean(), a.std()
b = np.array([x for x in a if x < (m-s) or x > (m+s)])
print("The numbers whicha are either less than (mean-std) OR greater than (mean+std) are the following: ", b)

The numbers whicha are either less than (mean-std) OR greater than (mean+std) are the following:  [83 94 21  7 14  3 16]


In [25]:
#4
odd = np.array([x for x in a if x%2 != 0 and  x < a.mean()])
print("The odd numbers which are less than the mean is the following: ", odd)
even = np.array([x for x in a if x%2 == 0 and  x > a.mean()])
print("The even numbers which are greater than the mean is the following: ", even)

The odd numbers which are less than the mean is the following:  [21 31  7  3 49]
The even numbers which are greater than the mean is the following:  [94 76 78 66]


### Exercise 4 Assigning via indexes

(1) Create a NumPy array of 40 random integers, from 0-100.

(2) Find all numbers that are within 1 standard deviation of the mean,
    and set them to be equal to the mean.  Has the mean changed?  Has
    the std changed?

(3) Create another NumPy array of 10 random integers, from 0-100.

(4) Set the item at the even indexes to be equal to the items at the odd
    indexes.  So index 0 will get the value at index 1, etc.


In [26]:
#1
a = np.random.randint(0, 101, 40)
prev_mean, prev_std = m,s = a.mean(), a.std()
print("The randomly generated array is ", a)

The randomly generated array is  [ 56  84  75  22  81  27  32  67   5  62  93  84  35  35  68  33  33  11
   0  92  44 100  44   4  73  41  13  82  71  81   2  35  31  18   4  78
  47  30  52  96]


In [27]:
#2
a[(a<m+s) & (a>m-s)]=a.mean()
if prev_mean != a.mean():
    print(f"The mean has changed from {prev_mean} to {a.mean()}.")
else:
    print("The mean has not changed.")
if prev_std != a.std():
    print(f"The standard deviation has changed from {prev_std} to {a.std()}.")
else:
    print("standard deviation has not changed.")

The mean has changed from 48.525 to 48.85.
The standard deviation has changed from 29.733808619145982 to 26.693210747304263.


In [28]:
#3
b = np.random.randint(0,101,10)
print("The other randomly generated array with 10 integers is: ", b)

The other randomly generated array with 10 integers is:  [61 58 72 57 76  6 51  4 16 87]


In [29]:
#4
for i in range(0, len(b), 2):
    b[i] = b[i+1]
print("The newly formed array is: ", b)

The newly formed array is:  [58 58 57 57  6  6  4  4 87 87]


### Exercise 5 Data types

(1) Create a NumPy array of 10 random integers from 0-100.

(2) Calculate the mean, which will be a float.

(3) Create an array of type float based on it, and replace the
    outliers (i.e., <mean-std or >mean+std) with the mean.

(4) Create a NumPy array of 20 random floats from 0-100.

(5) Replace those numbers whose int portion is even with the mean.
    (So 20.5 would be replaced, but 21.5 would not be.)

In [30]:
#1
a = np.random.randint(0, 101, 10)
print("The randomly generated array is ", a)

The randomly generated array is  [12 87 78 13 60 96 23 63 68 23]


In [31]:
#2
print(f"The mean of the array {a} is {round((a.mean()),2)}")

The mean of the array [12 87 78 13 60 96 23 63 68 23] is 52.3


In [32]:
#3
b = np.random.normal(a.mean(), a.std(), 10)
b = np.array([x for x in b if ((x<b.mean()+b.std()) and (x>b.mean()-b.std()))])
print("The array after replacing the outliers is: ", b)

The array after replacing the outliers is:  [65.08010907 36.25087584 64.25451319 66.6241514  75.11625878 62.06096631
 76.72741925]


In [33]:
#4
f = np.random.uniform(0.0, 100.000000001, 20)
print("The random float number array is:\n", f)

The random float number array is:
 [21.3772915   0.6219973  60.77841761 90.17553468 77.73657994 41.27949539
 23.61402578 33.61356549 15.25211246 26.20444176  8.23032773 95.54444318
  7.17875781 92.23042727 34.99052792 13.34900169 68.82426642 23.24925272
  0.1725162  50.83498998]


In [34]:
#5
mean_f = f.mean()
for i in range(len(f)):
    if int(f[i])%2 == 0:
        f[i] = mean_f
print("The array after the changes is:\n", f)

The array after the changes is:
 [21.3772915  39.26289864 39.26289864 39.26289864 77.73657994 41.27949539
 23.61402578 33.61356549 15.25211246 39.26289864 39.26289864 95.54444318
  7.17875781 39.26289864 39.26289864 13.34900169 39.26289864 23.24925272
 39.26289864 39.26289864]


### Exercise 6 nan

(1) Create a NumPy array of 30 random ints from 0-1000.

(2) Find the numbers that are <mean-std or >mean+std, and set them to
    be nan

(3) Now change those nan values to be the mean of the array's
    elements.

In [35]:
#1
a = np.random.randint(0,1001,30)
print("The randomly generated array is:\n", a)

The randomly generated array is:
 [308  87 279 625 858 620 913 167 668 118 514 117 781  25 554 631 548 310
 526 269 656 117 893 500 816 396 546 630 355 292]


In [36]:
#2
m, s = a.mean(), a.std()
a = np.array([np.NaN if ((x<m+s) and (x>m-s)) else x for x in a])
print("The array after setting replacing values with nan:\n", a)

The array after setting replacing values with nan:
 [ nan  87.  nan  nan 858.  nan 913. 167.  nan 118.  nan 117. 781.  25.
  nan  nan  nan  nan  nan  nan  nan 117. 893.  nan 816.  nan  nan  nan
  nan  nan]


In [37]:
for i in np.where(np.isnan(a)):
    a[i] = np.nanmean(a)
print("The array after replacing nan values with the mean:\n", a)

The array after replacing nan values with the mean:
 [444.72727273  87.         444.72727273 444.72727273 858.
 444.72727273 913.         167.         444.72727273 118.
 444.72727273 117.         781.          25.         444.72727273
 444.72727273 444.72727273 444.72727273 444.72727273 444.72727273
 444.72727273 117.         893.         444.72727273 816.
 444.72727273 444.72727273 444.72727273 444.72727273 444.72727273]


### Exercise 7 Multidimensional NumPy

(1) Create a 2-dimensional NumPy array of 45 random integers, from 0-100.

(2) Retrieve the elements at row index 2.

(3) Retrieve the elements at column index 3.

(4) Retrieve the elements at row indexes 1 and 4.

(5) Retrieve the elements at column indexes 1 and 4.

(6) Get the mean of the even numbers in row index 4.

(7) Get the mean of the odd numbers in column index 4.

In [38]:
#1
a = np.random.randint(0, 100, [5,9])
print("The two-dimensional NumPy array is:\n", a)

The two-dimensional NumPy array is:
 [[32 57 70 14 71 52 97 56 32]
 [83 18 95 73 80 82 32 63 58]
 [80 69 76 75  5 72 60 87 66]
 [57 56 66 10 44 89 41 17  8]
 [46 70 74 17 73 33  1 20 16]]


In [39]:
#2
print("The elements at row index 2 are: ", a[2])

The elements at row index 2 are:  [80 69 76 75  5 72 60 87 66]


In [40]:
#3
print("The elements at column index 3 are: ", a[:,3])

The elements at column index 3 are:  [14 73 75 10 17]


In [41]:
#4
print("The elements at row indexes 1 and 4 are:\n", a[[1,4]])

The elements at row indexes 1 and 4 are:
 [[83 18 95 73 80 82 32 63 58]
 [46 70 74 17 73 33  1 20 16]]


In [42]:
#5
print("The elements at column indexes 1 and 4 are:\n", a[:,[1,4]])

The elements at column indexes 1 and 4 are:
 [[57 71]
 [18 80]
 [69  5]
 [56 44]
 [70 73]]


In [43]:
#6
even = np.array([x for x in a[4] if x%2==0])
print("The mean of the even numbers in row index 4 is: ", even.mean())

The mean of the even numbers in row index 4 is:  45.2


In [44]:
#7
odd = np.array([x for x in a[4] if x%2!=0])
print("The mean of the odd numbers in row index 4 is: ", odd.mean())

The mean of the odd numbers in row index 4 is:  31.0


### Exercise 8 More Multidimensional

(1) Create a 6x6 NumPy array with random integers from 0-100.

(2) What is the mean of each column?

(3) Replace all even numbers in the array with twice their values. (So
    20 will become 40, and 40 will become 80.)

(4) Once again, calculate the mean of each column

(5) Now transpose the array and calculate the mean of each row.  Is it
    the same as you got before?

(6) Now sort each of the columns in the transposed array.  What does
    it look like now?

In [45]:
#1
a = np.random.randint(0, 101, [6,6])
print("The 6x6 NumPy array with random integers from 0-100 is:\n", a)

The 6x6 NumPy array with random integers from 0-100 is:
 [[81 40 94 58 72 22]
 [42 79  4 94 67 36]
 [75  8 19 14 66 24]
 [77 96 22 37 35 97]
 [ 2 54  5 72 91 23]
 [ 1 96  2 44 14 97]]


In [46]:
#2
for i in range(6):
    print(f"The mean of column with index {i} is: {a[:,i].mean()}")

The mean of column with index 0 is: 46.333333333333336
The mean of column with index 1 is: 62.166666666666664
The mean of column with index 2 is: 24.333333333333332
The mean of column with index 3 is: 53.166666666666664
The mean of column with index 4 is: 57.5
The mean of column with index 5 is: 49.833333333333336


In [47]:
#3
a_new = np.where(a%2==0, a*2, a)
print(a_new)

[[ 81  80 188 116 144  44]
 [ 84  79   8 188  67  72]
 [ 75  16  19  28 132  48]
 [ 77 192  44  37  35  97]
 [  4 108   5 144  91  23]
 [  1 192   4  88  28  97]]


In [48]:
#4
for i in range(6):
    print(f"The mean of column with index {i} is in the new array is: {a_new[:,i].mean()}")

The mean of column with index 0 is in the new array is: 53.666666666666664
The mean of column with index 1 is in the new array is: 111.16666666666667
The mean of column with index 2 is in the new array is: 44.666666666666664
The mean of column with index 3 is in the new array is: 100.16666666666667
The mean of column with index 4 is in the new array is: 82.83333333333333
The mean of column with index 5 is in the new array is: 63.5


In [49]:
#5
a_T = a.T
for i in range(6):
    print(f"The mean of row with index {i} is: {a_T[i].mean()}")
#The result will be identical to the part_2 as the multidimensional arrayy or matrix is now transposed.
#Hence the new row is the old columns of the matrix
#Therefore, the mean will remain unaltered

The mean of row with index 0 is: 46.333333333333336
The mean of row with index 1 is: 62.166666666666664
The mean of row with index 2 is: 24.333333333333332
The mean of row with index 3 is: 53.166666666666664
The mean of row with index 4 is: 57.5
The mean of row with index 5 is: 49.833333333333336


In [50]:
#6
print("The sorted transposed array looks like the following:\n", 
      a_T[a_T.argsort(axis=0), np.arange(a_T.argsort(axis=0).shape[1])])

The sorted transposed array looks like the following:
 [[22  4  8 22  2  1]
 [40 36 14 35  5  2]
 [58 42 19 37 23 14]
 [72 67 24 77 54 44]
 [81 79 66 96 72 96]
 [94 94 75 97 91 97]]
